### ISSUE TITLE
Clarifications on Success Rate Calculation and Initial Conditions for Tasks

### ISSUE THREAD

**Issue by jjleejj85** [DeckardAgent/deckard#2]
Hi, Kolby, I've been reading your paper with great interest, and I find the results presented in Figure 4 particularly intriguing. However, I have a couple of questions regarding the success rate calculations and the initial conditions for the experiments that I hope you could clarify:

1. Could you please elaborate on how the success rates were determined for the different tasks? Specifically, does the success rate represent the proportion of successful trials out of the total number of trials conducted within the allotted steps for each task (i.e., 1,000 steps for collectable items and 5,000 steps for craftable items)?
2. With respect to the initial conditions set for the success rate experiments, could you elaborate on whether the agents are equipped with any tools or resources at the outset of tasks? For instance, in the task of collecting cobblestone, is the agent provided with a wooden pickaxe from the start, or must it acquire one through its own actions in the environment?

I believe these details would greatly enhance the understanding of your experimental setup and the robustness of DECKARD's performance. Thank you for your time and consideration in addressing these inquiries.

**Comment by kolbytn** [comment]
1. Yes that is exactly right. The numbers in Figure 4 show the % of trials in which the agent successfully collected or crafted the item. If the agent went beyond the maximum number of time steps, the trial was considered a failure.
2. The agent always started with an empty inventory in all tasks.
